java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 1) -i 1000000 -f 10000" > HF1.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 2) -i 1000000 -f 10000" > HF2.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 3) -i 1000000 -f 10000" > HF3.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 4) -i 1000000 -f 10000" > HF4.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 5) -i 1000000 -f 10000" > HF5.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 6) -i 1000000 -f 10000" > HF6.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 7) -i 1000000 -f 10000" > HF7.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 8) -i 1000000 -f 10000" > HF8.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 9) -i 1000000 -f 10000" > HF9.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 10) -i 1000000 -f 10000" > HF10.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 11) -i 1000000 -f 10000" > HF11.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 12) -i 1000000 -f 10000" > HF12.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 13) -i 1000000 -f 10000" > HF13.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 14) -i 1000000 -f 10000" > HF14.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 15) -i 1000000 -f 10000" > HF15.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 16) -i 1000000 -f 10000" > HF16.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 17) -i 1000000 -f 10000" > HF17.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 18) -i 1000000 -f 10000" > HF18.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 19) -i 1000000 -f 10000" > HF19.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 20) -i 1000000 -f 10000" > HF20.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 21) -i 1000000 -f 10000" > HF21.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 22) -i 1000000 -f 10000" > HF22.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 23) -i 1000000 -f 10000" > HF23.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 24) -i 1000000 -f 10000" > HF24.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 25) -i 1000000 -f 10000" > HF25.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 26) -i 1000000 -f 10000" > HF26.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 27) -i 1000000 -f 10000" > HF27.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 28) -i 1000000 -f 10000" > HF28.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 29) -i 1000000 -f 10000" > HF29.csv
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l trees.HoeffdingTree -s (generators.RandomTreeGenerator -i 30) -i 1000000 -f 10000" > HF30.csv